workflows:
  ios:
    name: iOS Workflow
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build app
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.ipa
  android:
    name: Android Workflow
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build app
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
